### PR TITLE
Password reset

### PR DESCRIPTION
**Pull request by machristie**
For issue #1053. I'll fix the merge conflicts shortly.

### CODE REVIEW

**Comment by BlakeDraper** [comment]
@machristie since merging your PR #1085 into `sgci_staging`, merge conflicts have been introduced. Can you pull down and merge the current state of `sgci_staging` branch with `password_reset` and then re-push to `password_reset` to update this PR and make it auto-mergeable?

**Comment by BlakeDraper** [comment]
@machristie sent you an email about this. I see that missed your PR order request, so see email for options to correct. Thanks!

**Comment by machristie** [comment]
@BlakeDraper I've merged in sgci_staging now

**Review by BlakeDraper — APPROVED** [review]
No issues spotted.

**Pull request merged**
